# Generated by Django 5.2.4 on 2025-07-10 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("client", "Client"), ("trainer", "Antrenor")],
                        max_length=10,
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "trainer"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="BeStrong.userprofile",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
