# Generated by Django 5.2.4 on 2025-07-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BeStrong", "0002_workoutplan"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
