# Generated by Django 5.2.4 on 2025-07-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BeStrong", "0003_userprofile_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workoutplan",
            name="day",
            field=models.DateField(),
        ),
    ]
