# Generated by Django 5.2.4 on 2025-07-17 08:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BeStrong", "0004_alter_workoutplan_day"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="workoutplan",
            old_name="day",
            new_name="date",
        ),
        migrations.AlterUniqueTogether(
            name="workoutplan",
            unique_together={("client", "date")},
        ),
    ]
